//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassRegister.Data
{
    using System;
    using System.Collections.Generic;

    /// <auto-generated/>
    public partial class BERLET
    {
        /// <auto-generated/>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BERLET()
        {
            this.VASARLAS = new HashSet<VASARLAS>();
        }

        /// <auto-generated/>
        public int BERLET_ID { get; set; }
        /// <auto-generated/>
        public string MEGNEVEZES { get; set; }
        /// <auto-generated/>
        public Nullable<decimal> AR { get; set; }
        /// <auto-generated/>
        public Nullable<decimal> ERVENYESSEG_IDO { get; set; }
        /// <auto-generated/>
        public string KEDVEZMENY_TIPUS { get; set; }
        /// <auto-generated/>
        public string BERLET_FORMATUM { get; set; }

        /// <auto-generated/>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASARLAS> VASARLAS { get; set; }
    }
}
