//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassRegister.Data
{
    using System;
    using System.Collections.Generic;

    /// <auto-generated/>
    public partial class DOLGOZO
    {
        /// <auto-generated/>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOLGOZO()
        {
            this.VASARLAS = new HashSet<VASARLAS>();
        }

        /// <auto-generated/>
        public int DOLGOZO_ID { get; set; }
        /// <auto-generated/>
        public int CEG_ID { get; set; }
        /// <auto-generated/>
        public string NEV { get; set; }
        /// <auto-generated/>
        public string NEM { get; set; }
        /// <auto-generated/>
        public string SZULETESI_HELY { get; set; }
        /// <auto-generated/>
        public Nullable<decimal> SZULETESI_EV { get; set; }
        /// <auto-generated/>
        public Nullable<decimal> IGAZOLVANY_SZAM { get; set; }

        /// <auto-generated/>
        public virtual CEG CEG { get; set; }
        /// <auto-generated/>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASARLAS> VASARLAS { get; set; }
    }
}
