//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassRegister.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOLGOZO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOLGOZO()
        {
            this.VASARLAS = new HashSet<VASARLAS>();
        }
    
        public decimal DOLGOZO_ID { get; set; }
        public decimal CEG_ID { get; set; }
        public string NEV { get; set; }
        public string NEM { get; set; }
        public string SZULETESI_HELY { get; set; }
        public Nullable<decimal> SZULETESI_EV { get; set; }
        public Nullable<decimal> IGAZOLVANY_SZAM { get; set; }
    
        public virtual ICollection<CEG> CEG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VASARLAS> VASARLAS { get; set; }
    }
}
