//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassRegister.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <auto-generated/>
    public partial class PassRegisterDatabaseEntities : DbContext
    {
        /// <auto-generated/>
        public PassRegisterDatabaseEntities()
            : base("name=PassRegisterDatabaseEntities")
        {
        }

        /// <auto-generated/>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /// <auto-generated/>
        public virtual DbSet<BERLET> BERLET { get; set; }
        /// <auto-generated/>
        public virtual DbSet<CEG> CEG { get; set; }
        /// <auto-generated/>
        public virtual DbSet<DOLGOZO> DOLGOZO { get; set; }
        /// <auto-generated/>
        public virtual DbSet<VASARLAS> VASARLAS { get; set; }
    }
}
