//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassRegister.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VASARLAS
    {
        public decimal VASARLAS_ID { get; set; }
        public decimal DOLGOZO_ID { get; set; }
        public decimal BERLET_ID { get; set; }
        public string BERLET_MEGNEVEZES { get; set; }
        public Nullable<decimal> IGAZOLVANY_SZAM { get; set; }
        public Nullable<System.DateTime> ERVENYESSEG_KEZDETE { get; set; }
    
        public virtual BERLET BERLET { get; set; }
        public virtual DOLGOZO DOLGOZO { get; set; }
    }
}
