//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassRegister.Data
{
    using System;
    using System.Collections.Generic;

    /// <auto-generated/>
    public partial class VASARLAS
    {
        /// <auto-generated/>
        public int VASARLAS_ID { get; set; }
        /// <auto-generated/>
        public int DOLGOZO_ID { get; set; }
        /// <auto-generated/>
        public int BERLET_ID { get; set; }
        /// <auto-generated/>
        public string BERLET_MEGNEVEZES { get; set; }
        /// <auto-generated/>
        public Nullable<decimal> IGAZOLVANY_SZAM { get; set; }
        /// <auto-generated/>
        public Nullable<System.DateTime> ERVENYESSEG_KEZDETE { get; set; }

        /// <auto-generated/>
        public virtual BERLET BERLET { get; set; }
        /// <auto-generated/>
        public virtual DOLGOZO DOLGOZO { get; set; }
    }
}
