// <auto-generated/>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PassRegister.Program
{
    class Menu
    {
        public Menu()
        {
            MainMenu();
        }
        public void MainMenu()
        {
            Console.Clear();
            Console.WriteLine("0 ) Exit");
            Console.WriteLine("1 ) Bérletek tábla műveletek");
            Console.WriteLine("2 ) Dolgozó tábla műveletek");
            Console.WriteLine("3 ) Cég tábla műveletek");
            Console.WriteLine("4 ) Vásárlás tábla műveletek");
            Console.WriteLine("5 ) Adott bérletet vevő emberek neve");
            Console.WriteLine("6 ) Legalabb 2en megvették bérletek");
            Console.WriteLine("7 ) Kedvezmény nélküli bérletet vett emberek születési éve");
            Console.WriteLine("8 ) JAVA");
            int valasztas = int.Parse(Console.ReadLine());
            switch (valasztas)
            {
                case 0:
                    Console.Clear();
                    MainMenu();
                    break;
                case 1:
                    Console.Clear();
                    CRUD("Bérletek tábla műveletek");
                    break;
                case 2:
                    Console.Clear();
                    CRUD("Dolgozó tábla műveletek");
                    break;
                case 3:
                    Console.Clear();
                    CRUD("Cég tábla műveletek");
                    break;
                case 4:
                    Console.Clear();
                    CRUD("Vásárlás tábla műveletek");
                    break;
                case 5:
                    Console.Clear();
                    Console.WriteLine("nincs kész");
                    break;
                case 6:
                    Console.Clear();
                    Console.WriteLine("nincs kész");
                    break;
                case 7:
                    Console.Clear();
                    Console.WriteLine("nincs kész");
                    break;
                case 8:
                    Console.Clear();
                    Console.WriteLine("nincs kész");
                    break;
            }
        }
        public void CRUD(string whichOne)
        {
            Console.WriteLine(whichOne+"\n");
            Console.WriteLine("0) Back");
            Console.WriteLine("1) Listázás");
            Console.WriteLine("2) Hozzáadás");
            Console.WriteLine("3) Módosítás");
            Console.WriteLine("4) Törlés");
            int valasztas = int.Parse(Console.ReadLine());
            switch (valasztas)
            {
                case 0:
                    Console.Clear();
                    MainMenu();
                    break;
                case 1:
                    Console.WriteLine("nincs kész");
                    break;
                case 2:
                    Console.WriteLine("nincs kész");
                    break;
                case 3:
                    Console.WriteLine("nincs kész");
                    break;
                case 4:
                    Console.WriteLine("nincs kész");
                    break;
            }

        }
    }
}
